# Generated by Django 5.1.7 on 2025-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_image_portfolioinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='github',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='projects',
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
