# Generated by Django 5.1.7 on 2025-04-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolioinfo_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='degree_name',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='phone_number',
        ),
    ]
