# Generated by Django 5.1.7 on 2025-04-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolioinfo_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinfo',
            name='name',
            field=models.CharField(default='Federico Maciel', max_length=250),
        ),
    ]
