# Generated by Django 5.1.7 on 2025-04-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolioinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinfo',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='degree_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='job_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
