# Generated by Django 5.1.7 on 2025-04-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfolioinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioinfo',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='./core/static/core/img/'),
        ),
    ]
