# Generated by Django 5.1.7 on 2025-04-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolioinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinfo',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
