# Generated by Django 5.1.7 on 2025-04-17 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolioinfo_price_alter_portfolioinfo_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioinfo',
            options={'verbose_name': 'Portoflio Info', 'verbose_name_plural': 'Portoflio Info'},
        ),
    ]
