# Generated by Django 5.1.7 on 2025-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_portfolioinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioinfo',
            name='name',
            field=models.CharField(default='Nombre completo', max_length=250),
        ),
    ]
